
export const diputadosData = [
  {
    nombre: "Carla Noelia Aliendro",
    departamento: "Chamical",
    partido: "Agrupación Muniipal Vecinalismo Chamicalense",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó II",
    direccion: "Copiapó 258",
    foto: "/fotos/aliendro.png",
  },
  {
    nombre: "María Gabriela Amoroso Fernández",
    departamento: "Capital",
    partido: "Frente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2025",
    anexo: "Anexo",
    direccion: "Av. Principal 456, Chilecito",
    foto: "/fotos/amoroso.png",
  },
  {
    nombre: "Luis Cleto Arce Agüero",
    departamento: "Rosario Vera Peñaloza",
    partido: "Frente Federal",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2025",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/arce.png",
  },
  {
    nombre: "Raúl Eduardo Cabral",
    departamento: "Chilecito",
    partido: "Partido de la Victoria",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó II",
    direccion: "Copiapó 258",
    foto: "/fotos/cabral.png",
  },
  {
    nombre: "Jesús Omar Castro",
    departamento: "General Angel Vicente Peñaloza",
    partido: "Frente Federal",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó II",
    direccion: "Copiapó 258",
    foto: "/fotos/castro.png",
  },
  {
    nombre: "Oscar Eduardo Chamía",
    departamento: "General Felipe Varela",
    partido: "Frente Federal",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Urquiza",
    direccion: "Urquiza 445",
    foto: "/fotos/chamia.png",
  },
  {
    nombre: "Luis Alberto Chumbita",
    departamento: "Chamical",
    partido: "Agrupación Muniipal Vecinalismo Chamicalense",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó II",
    direccion: "Copiapó 258",
    foto: "/fotos/chumbita.png",
  },
  {
    nombre: "José Abrahán Couceiro",
    departamento: "General San Martín",
    partido: "Frente Federal",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Urquiza",
    direccion: "Urquiza 445",
    foto: "/fotos/couceiro.png",
  },
  {
    nombre: "Fernando Exequiel Delgado",
    departamento: "Castro Barros",
    partido: "Freente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Urquiza",
    direccion: "Urquiza 445",
    foto: "/fotos/delgado.png",
  },
  {
    nombre: "Juan José Elías",
    departamento: "Chamical",
    partido: "Provincial Peronista sin Fronteras",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo urquiza",
    direccion: "Urquiza 445",
    foto: "/fotos/elias.png",
  },
  {
    nombre: "Mario Gustavo Galván",
    departamento: "Capital",
    partido: "Vamos la Rioja",
    bloque: "UCR (Unión Cívica Radical)",
    mandato: "2021 - 2025",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/galvan.png",
  },
  {
    nombre: "Fabián Nicolás Gauna",
    departamento: "General Ortiz de Ocampo",
    partido: "Momiento Provincial Integración Popular",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó II",
    direccion: "copiapó 258",
    foto: "/fotos/gauna.png",
  },
  {
    nombre: "Antonio Roberto Godoy",
    departamento: "Rosario Vera Peñaloza",
    partido: "Frente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Norte",
    direccion: "Anexo",
    foto: "/fotos/godoy.png",
  },
  {
    nombre: "Hernán Gabriel Gurgone Flores",
    departamento: "Sanagasta",
    partido: "Frente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Urquiza",
    direccion: "urquiza 445",
    foto: "/fotos/gurgone.png",
  },
  {
    nombre: "Sebastián Gutiérrez",
    departamento: "Chilecito",
    partido: "Contruyamos Juntos",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Copiapó II",
    direccion: "Copiapó 258",
    foto: "/fotos/gutierrez.png",
  },
  {
    nombre: "Sofía Lorena Laso",
    departamento: "Famatina",
    partido: "Frente Federal",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/laso.png",
  },
  {
    nombre: "Pablo Darío Leo",
    departamento: "Arauco",
    partido: "Frente Federal",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó II",
    direccion: "Copiapó 258",
    foto: "/fotos/leo.png",
  },
  {
    nombre: "Mauro Claudio Lujan",
    departamento: "General San Martin",
    partido: "Frente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/lujan.png",
  },
  {
    nombre: "Mirtha María Teresita Luna",
    departamento: "Capital",
    partido: "Norte Grande",
    bloque: "Norte Grande",
    mandato: "2021 - 2025",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/luna.png",
  },
  {
    nombre: "Carlos Alberto Machicote",
    departamento: "Capital",
    partido: "Frente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Casa Central",
    direccion: "Dalamacio Velez 874",
    foto: "/fotos/machicote.png",
  },
  {
    nombre: "Nicolás Antonio Martínez",
    departamento: "Arauco",
    partido: "Lealtad y Dignidad",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Urquiza",
    direccion: "Urquiza 445",
    foto: "/fotos/martinez.png",
  },
  {
    nombre: "María Liliana Medina",
    departamento: "Capital",
    partido: "La Libertad Avanza",
    bloque: "La Libertad Avanza",
    mandato: "2023 - 2025",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/medina.png",
  },
  {
    nombre: "Paul Alberto Mercado",
    departamento: "General Belgrano",
    partido: "Lenvantemos Belgano",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Urquiza",
    direccion: "Urquiza 445",
    foto: "/fotos/mercado.png",
  },
  {
    nombre: "Egle Maricel Muñoz",
    departamento: "General Felipe Varela",
    partido: "Frente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Urquiza",
    direccion: "Urquiza 445",
    foto: "/fotos/munoz.png",
  },
  {
    nombre: "Natalia Noelia Oros",
    departamento: "Independencia",
    partido: "Parido de la Victoria",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó II",
    direccion: "Copiapó 258",
    foto: "/fotos/oros.png",
  },
  {
    nombre: "Lourdes Alejandrina Ortiz",
    departamento: "Capital",
    partido: "Frente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Copiapó II",
    direccion: "Copiapó 258",
    foto: "/fotos/ortiz.png",
  },
  {
    nombre: "Cristian Eduardo Pérez",
    departamento: "Rosario Vera Peñaloza",
    partido: "Frente Federal",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/perez.png",
  },
  {
    nombre: "Julio César Reinoso",
    departamento: "Arauco",
    partido: "Frente Federal",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó II",
    direccion: "Copiapó 258",
    foto: "/fotos/reinoso.png",
  },
  {
    nombre: "Nadina Verónica Reynoso",
    departamento: "Capital",
    partido: "Hay Futuro",
    bloque: "Hay Futuro",
    mandato: "2021 - 2025",
    anexo: "Anexo Urquiza",
    direccion: "Urquiza 445",
    foto: "/fotos/reynoso.png",
  },
  {
    nombre: "Gabriela Azucena Rodríguez",
    departamento: "Chilecito",
    partido: "Juntos por el Cambio Union Cívica Radical",
    bloque: "Union Cívica Radical",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/rodriguez.png",
  },
  {
    nombre: "Luis Lisandro Rojo",
    departamento: "General La Madrid",
    partido: "Frente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/rojo.png",
  },
  {
    nombre: "Mario Claudio Ruíz",
    departamento: "Chilecito",
    partido: "Partido Ciudadano",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Urquiza",
    direccion: "Urquiza 445",
    foto: "/fotos/ruiz.png",
  },
  {
    nombre: "Juan Carlos Santander",
    departamento: "Capital",
    partido: "Frente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/santander.png",
  },
  {
    nombre: "Alejandro Norberto Verazay",
    departamento: "Vinchina",
    partido: "Frente Federal",
    bloque: "Bloque Justicialista",
    mandato: "2021 - 2025",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/verazay.png",
  },
  {
    nombre: "Luis Alberto Villagra",
    departamento: "General Felipe Varela",
    partido: "Frente Federal",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2025",
    anexo: "Anexo Copiapó II",
    direccion: "Copiapó 258",
    foto: "/fotos/villagra-luis.png",
  },
  {
    nombre: "Silvio Horacio Villagra",
    departamento: "San Blas de los Sauces",
    partido: "Frente de Todos",
    bloque: "Bloque Justicialista",
    mandato: "2023 - 2027",
    anexo: "Anexo Copiapó I",
    direccion: "Copiapó y Rivadavia",
    foto: "/fotos/villagra-silvio.png",
  },
];
