
export const diputadosData = [
  { nombre: "Carla Noelia Aliendro", departamento: "Chamical", partido: "PJ" },
  { nombre: "María Gabriela Amoroso Fernández", departamento: "Chilecito", partido: "PJ" },
  { nombre: "Luis Cleto Arce Agüero", departamento: "Rosario Vera Peñaloza", partido: "PJ" },
  { nombre: "Raúl Eduardo Cabral", departamento: "Chilicito", partido: "PJ" },
  { nombre: "Jesús Omar Castro", departamento: "Rosario Vera Peñaloza", partido: "PJ" },
  { nombre: "Oscar Eduardo Chamía", departamento: "General Felipe Varela", partido: "PJ" },
  { nombre: "Luis Alberto Chumbita", departamento: "Chamical", partido: "PJ" },
  { nombre: "José Abrahán Couceiro", departamento: "General San Martin", partido: "PJ" },
  { nombre: "Fernando Exequiel Delgado", departamento: "Castro Barros", partido: "PJ" },
  { nombre: "Juan José Elías", departamento: "Chamical", partido: "PJ" },
  { nombre: "Mario Gustavo Galván", departamento: "Capital", partido: "UCR" },
  { nombre: "Fabián Nicolás Gauna", departamento: "General Ortiz de Ocampo", partido: "PJ" },
  { nombre: "Antonio Roberto Godoy", departamento: "Rozario Vera Peñaloza", partido: "PJ" },
  { nombre: "Hernán Gabriel Gurgone Flores", departamento: "Sanagasta", partido: "PJ" },
  { nombre: "Sebastían Gutiérrez", departamento: "Chilecito", partido: "PJ" },
  { nombre: "Sofía Lorena Laso", departamento: "Famatina", partido: "PJ" },
  { nombre: "Pablo Darío Leo", departamento: "Arauco", partido: "PJ" },
  { nombre: "Mirtha María Teresita Luna", departamento: "Capital", partido: "PJ" },
  { nombre: "Carlos Alberto Machicote", departamento: "Capital", partido: "PJ" },
  { nombre: "Nicolás Antonio Martínez", departamento: "Arauco", partido: "PJ" },
  { nombre: "María Liliana Medina", departamento: "Capital", partido: "Livertad Avanza" },
  { nombre: "Paul Alberto Mercado", departamento: "General Belgrano", partido: "PJ" },
  { nombre: "Egle Maricel Muñoz", departamento: "General Felipe Varela", partido: "PJ" },
  { nombre: "Natalia Noelia Oros", departamento: "Indepencia", partido: "PJ" },
  { nombre: "Lourdes Alejandrina Ortiz", departamento: "Capital", partido: "PJ" },
  { nombre: "Cristian Eduardo Pérez", departamento: "Rosario Vera Peñaloza", partido: "PJ" },
  { nombre: "Julio César Reinoso", departamento: "Arauco", partido: "PJ" },
  { nombre: "Nadina Verónica Reynoso", departamento: "Capital", partido: "Hay Futuro" },
  { nombre: "Gabriela Azucena Rodríguez", departamento: "Chilecito", partido: "UCR" },
  { nombre: "Luis Lisandro Rojo", departamento: "General la Madrid", partido: "PJ" },
  { nombre: "Mario Claudio Ruíz", departamento: "Chilecito", partido: "PJ" },
  { nombre: "Juan Carlos Santander", departamento: "Capital", partido: "PJ" },
  { nombre: "Alejandro Norberto Verazay", departamento: "Vinchina", partido: "PJ" },
  { nombre: "Luis Alberto Villagra", departamento: "General Felipe Varela", partido: "PJ" },
  { nombre: "Silvio Horacio Villagra", departamento: "San Blas de los Sauces", partido: "PJ" },
];