
export const diputadosData = [
  { nombre: "Carla Noelia Aliendro", 
    departamento: "Chamical", 
    partido: "PJ",
    foto: "/fotos/aliendro.png",
  },
  { nombre: "María Gabriela Amoroso Fernández", 
    departamento: "Chilecito", 
    partido: "PJ",
     foto: "/fotos/amoroso.png",
  },
  { nombre: "Luis Cleto Arce Agüero", 
    departamento: "Rosario Vera Peñaloza", 
    partido: "PJ",
    foto: "/fotos/arce.png",
  },
  { nombre: "Raúl Eduardo Cabral", 
    departamento: "Chilicito", 
    partido: "PJ",
     foto: "/fotos/cabral.png",
  },
  { nombre: "Jesús Omar Castro", 
    departamento: "Rosario Vera Peñaloza", 
    partido: "PJ",
     foto: "/fotos/castro.png",
  },
  { nombre: "Oscar Eduardo Chamía", 
    departamento: "General Felipe Varela", 
    partido: "PJ",
    foto: "/fotos/chamia.png",
  },
  { nombre: "Luis Alberto Chumbita", 
    departamento: "Chamical", 
    partido: "PJ",
    foto: "/fotos/chumbita.png",
  },
  { nombre: "José Abrahán Couceiro", 
    departamento: "General San Martin", 
    partido: "PJ",
    foto: "/fotos/couceiro.png",
  },
  { nombre: "Fernando Exequiel Delgado", 
    departamento: "Castro Barros", 
    partido: "PJ",
    foto: "/fotos/delgado.png",
  },
  { nombre: "Juan José Elías", 
    departamento: "Chamical", 
    partido: "PJ",
    foto: "/fotos/elias.png",
  },
  { nombre: "Mario Gustavo Galván", 
    departamento: "Capital", 
    partido: "UCR",
    foto: "/fotos/galvan.png",
  },
  { nombre: "Fabián Nicolás Gauna",
    departamento: "General Ortiz de Ocampo", 
    partido: "PJ",
    foto: "/fotos/gauna.png",
  },
  { nombre: "Antonio Roberto Godoy", 
    departamento: "Rozario Vera Peñaloza", 
    partido: "PJ",
    foto: "/fotos/godoy.png",
  },
  { nombre: "Hernán Gabriel Gurgone Flores", 
    departamento: "Sanagasta", 
    partido: "PJ",
    foto: "/fotos/gurgone.png",
  },
  { nombre: "Sebastían Gutiérrez", 
    departamento: "Chilecito", 
    partido: "PJ",
    foto: "/fotos/gutierrez.png",
  },
  { nombre: "Sofía Lorena Laso", 
    departamento: "Famatina", 
    partido: "PJ",
    foto: "/fotos/loso.png",
  },
  { nombre: "Pablo Darío Leo", 
    departamento: "Arauco", 
    partido: "PJ",
    foto: "/fotos/leo.png",
  },
  { nombre: "Mirtha María Teresita Luna", 
    departamento: "Capital", 
    partido: "PJ",
    foto: "/fotos/luna.png",
  },
  { nombre: "Carlos Alberto Machicote", 
    departamento: "Capital", 
    partido: "PJ",
    foto: "/fotos/machicote.png",
  },
  { nombre: "Nicolás Antonio Martínez", 
    departamento: "Arauco", 
    partido: "PJ",
    foto: "/fotos/martinez.png",
  },
  { nombre: "María Liliana Medina", 
    departamento: "Capital", 
    partido: "Livertad Avanza",
    foto: "/fotos/liliana-medina.png",
  },
  { nombre: "Paul Alberto Mercado", 
    departamento: "General Belgrano", 
    partido: "PJ",
    foto: "/fotos/mercado.png",
  },
  { nombre: "Egle Maricel Muñoz", 
    departamento: "General Felipe Varela", 
    partido: "PJ",
    foto: "/fotos/maricel-munoz.png",
  },
  { nombre: "Natalia Noelia Oros", 
    departamento: "Indepencia", 
    partido: "PJ",
    foto: "/fotos/oros.png",
  },
  { nombre: "Lourdes Alejandrina Ortiz", 
    departamento: "Capital", 
    partido: "PJ",
    foto: "/fotos/ortiz.png",
  },
  { nombre: "Cristian Eduardo Pérez", 
    departamento: "Rosario Vera Peñaloza", 
    partido: "PJ",
    foto: "/fotos/perez.png",
  },
  { nombre: "Julio César Reinoso", 
    departamento: "Arauco", 
    partido: "PJ",
    foto: "/fotos/reinoso.png",
  },
  { nombre: "Nadina Verónica Reynoso", 
    departamento: "Capital", 
    partido: "Hay Futuro",
    foto: "/fotos/reynoso.png",
  },
  { nombre: "Gabriela Azucena Rodríguez", 
    departamento: "Chilecito", 
    partido: "UCR",
    foto: "/fotos/rodriguez.png",
  },
  { nombre: "Luis Lisandro Rojo", 
    departamento: "General la Madrid", 
    partido: "PJ",
    foto: "/fotos/rojo.png",
  },
  { nombre: "Mario Claudio Ruíz", 
    departamento: "Chilecito", 
    partido: "PJ",
    foto: "/fotos/ruiz.png",
  },
  { nombre: "Juan Carlos Santander", 
    departamento: "Capital", 
    partido: "PJ",
    foto: "/fotos/santander.png",
  },
  { nombre: "Alejandro Norberto Verazay", 
    departamento: "Vinchina", 
    partido: "PJ",
    foto: "/fotos/verazay.png",
  },
  { nombre: "Luis Alberto Villagra", 
    departamento: "General Felipe Varela", 
    partido: "PJ",
    foto: "/fotos/villagra-luis.png",
  },
  { nombre: "Silvio Horacio Villagra", 
    departamento: "San Blas de los Sauces", 
    partido: "PJ",
    foto: "/fotos/villagra-silvio.png",
  },
];